apiVersion: 1

datasources:
  - name: AMG PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: amg
    user: amg
    secureJsonData:
      password: amg_password
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
    isDefault: true
    editable: true
